/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TripMode = IDL.Variant({
  'car' : IDL.Null,
  'bike' : IDL.Null,
  'walk' : IDL.Null,
  'transit' : IDL.Null,
});
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'mode' : TripMode,
  'origin' : IDL.Text,
  'distance' : IDL.Nat,
  'roundTrip' : IDL.Bool,
});

export const idlService = IDL.Service({
  'deleteTrip' : IDL.Func([IDL.Nat], [], []),
  'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [Trip], ['query']),
  'saveTrip' : IDL.Func(
      [IDL.Text, IDL.Text, TripMode, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'updateTrip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, TripMode, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TripMode = IDL.Variant({
    'car' : IDL.Null,
    'bike' : IDL.Null,
    'walk' : IDL.Null,
    'transit' : IDL.Null,
  });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'mode' : TripMode,
    'origin' : IDL.Text,
    'distance' : IDL.Nat,
    'roundTrip' : IDL.Bool,
  });
  
  return IDL.Service({
    'deleteTrip' : IDL.Func([IDL.Nat], [], []),
    'getAllTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [Trip], ['query']),
    'saveTrip' : IDL.Func(
        [IDL.Text, IDL.Text, TripMode, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'updateTrip' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, TripMode, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };